DROP TABLE TAGS CASCADE CONSTRAINTS;
DROP SEQUENCE tags_seq;


CREATE TABLE TAGS(
    tag_id        NUMBER       CONSTRAINT tag_name_pk PRIMARY KEY,
    tag_name      VARCHAR2(50) CONSTRAINT t_name_nn NOT NULL,
    url_tag      VARCHAR2(100) CONSTRAINT t_url_nn NOT NULL
);
ALTER TABLE TAGS
ADD CONSTRAINT tag_nm_un UNIQUE(tag_name);

CREATE SEQUENCE tags_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
ALTER TABLE TAGS
MODIFY tag_id DEFAULT tags_seq.NEXTVAL;
/